temperature: 0.5
top_p: 1
presence_penalty: 0.0
files:
  lan:
    test_file: './data_divided/sciqa-test-lan.json'
    output_file: './output/output_dg-sciqa-lan.json'
    results_file: './evaluation/sciq-lan.json'
  nat:
    test_file: './data_divided/sciqa-test-nat.json'
    output_file: './output/output_dg-sciqa-nat.json'
    results_file: './evaluation/sciq-nat.json'
  soc:
    test_file: './data_divided/sciqa-test-soc.json'
    output_file: './output/output_dg-sciqa-soc.json'
    results_file: './evaluation/sciq-soc.json'