temperature: 0.0
presence_penalty: 0.0
prompt_types:
  rule:
    rg: "rule_rg"
    dg: "rule_dg"
    format: "rule_format"
  cot:
    rg: "cot_rg"
    dg: "cot_dg"
    format: "cot_format"
  non:
    dg: "non_dg"

# 添加数据集映射配置
dataset_names:
  scienceqa: "derek-thomas/ScienceQA"  # HF数据集映射

# 添加模型映射配置
model_path:
  qwen7b: "/data/lzx/model/qwen2.5-7b-instruct"
  qwenvl: "/data/lzx/model/qwen2.5-vl-7b-instruct"

max_tokens:
  rg: 2048 # cot prompt 类型的 reasoning generation max_tokens
  dg: 512  # cot prompt 类型的 distractor generation max_tokens
    
files:
  lan:
    test_file: './data_divided/sciqa-test-lan.json'
    output_file: './output/output_dg-sciqa-lan'  
    results_file: './evaluation/sciqa-lan'        
  nat:
    test_file: './data_divided/sciqa-test-nat.json'
    output_file: './output/output_dg-sciqa-nat'   
    results_file: './evaluation/sciqa-nat'        
  soc:
    test_file: './data_divided/sciqa-test-soc.json'
    output_file: './output/output_dg-sciqa-soc'    
    results_file: './evaluation/sciqa-soc' 
  sciqa-text:
    test_file: './data_divided/sciqa-test-text.json'
    output_file: './output/output_dg-sciqa-text'    
    results_file: './evaluation/sciqa-text'         
  sciq:
    test_file: '/data/lzx/sciq/test.json'
    output_file: './output/output_dg-Sciq'         
    results_file: './evaluation/Sciq'   
  sciqa-all:
    test_file: './data_divided/sciqa-test.json'
    output_file: './output/output_dg-sciqa-all'    
    results_file: './evaluation/sciqa-all'
  scienceqa:  
    output_file: './output/output_dg-scienceqa'
    results_file: './evaluation/scienceqa'